github action now manual

diff --git a/.github/workflows/clang-format.yml b/.github/workflows/clang-format.yml
--- a/.github/workflows/clang-format.yml
+++ b/.github/workflows/clang-format.yml
@@ -1,39 +1,28 @@
-# .github/workflows/clang-format.yml
-# name: Auto-format with Clang Format
+name: Check Formatting
 
-# on:
-#     push:
-#         branches:
-#             - master
-#     pull_request:
-#         branches:
-#             - master
+on:
+    pull_request:
+        branches:
+            - master
 
-# jobs:
-#     format:
-#         runs-on: ubuntu-latest
+jobs:
+    format:
+        runs-on: ubuntu-latest
 
-#         steps:
-#             - name: Checkout the repository
-#               uses: actions/checkout@v3
+        steps:
+            - name: Checkout the repository
+              uses: actions/checkout@v3
 
-#             - name: Set up clang-format
-#               run: sudo apt-get install clang-format
+            - name: Set up clang-format
+              run: sudo apt-get install clang-format
 
-#             - name: Run clang-format
-#               run: |
-#                   find . -regex '.*\.\(cpp\|hpp\|cc\|hh\|c\|h\)' -exec clang-format -i {} \;
+            - name: Run clang-format
+              run: |
+                  find . -regex '.*\.\(cpp\|hpp\|cc\|hh\|c\|h\)' -exec clang-format -i {} \;
 
-#             - name: Commit changes
-#               run: |
-#                   git config --global user.name "github-actions[bot]"
-#                   git config --global user.email "github-actions[bot]@users.noreply.github.com"
-#                   git add .
-#                   git commit -m "Apply clang-format"
-#               continue-on-error: true
-
-#             - name: Push changes
-#               run: |
-#                   git pull
-#                   git push
-#               if: success()
+            - name: Check for uncommitted changes
+              run: |
+                  if [[ $(git status --porcelain) ]]; then
+                      echo "::error::Code is not formatted. Run clang-format locally or commit the changes."
+                      exit 1
+                  fi
